name: Build LineageOS GSI

on:
  workflow_dispatch:  # Запуск вручную

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_VERSION: "22.1"  
      DEVICE: "gsi_arm64-ab"   
      BRANCH: "lineage-22.1"  
      USE_CCACHE: "1"  
      CCACHE_SIZE: "60G"  

    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Проверяем переменные среды
        run: |
          echo "ANDROID_VERSION=${ANDROID_VERSION}"
          echo "DEVICE=${DEVICE}"
          echo "BRANCH=${BRANCH}"
          echo "USE_CCACHE=${USE_CCACHE}"
          echo "CCACHE_SIZE=${CCACHE_SIZE}"

      - name: Устанавливаем зависимости
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk bc bison build-essential \
          ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick \
          lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev \
          libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop \
          pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev \
          git-lfs jq

      - name: Включаем CCache
        run: |
          export USE_CCACHE=${USE_CCACHE}
          export CCACHE_EXEC=/usr/bin/ccache
          ccache -M ${CCACHE_SIZE}
          ccache -s

      - name: Устанавливаем repo (новую версию)
        run: |
          mkdir -p ~/bin
          curl -o ~/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
          chmod a+x ~/bin/repo
          echo "export PATH=$HOME/bin:$PATH" >> $GITHUB_ENV
          ~/bin/repo version

      - name: Клонируем LineageOS в `lineage-source`
        run: |
          mkdir -p ~/android/lineage
          cd ~/android/lineage
          repo init -u https://github.com/LineageOS/android.git -b ${BRANCH} --git-lfs
          repo sync -j$(nproc) || (echo "Ошибка при repo sync, пробуем снова..." && sleep 10 && repo sync -j1)

      - name: Подготавливаем GSI
        run: |
          cd ~/android/lineage
          source build/envsetup.sh
          lunch lineage_${DEVICE}-userdebug

      - name: Запускаем сборку GSI
        run: |
          cd ~/android/lineage
          mka systemimage -j$(nproc) | tee build.log

      - name: Загружаем GSI в Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lineage-gsi
          path: ~/android/lineage/out/target/product/${DEVICE}/system.img

      - name: Загружаем логи сборки
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: ~/android/lineage/build.log
