name: Update LineageOS Source (aka G(it), L(ineage remote), M(erge), U(pload))

on:
  schedule:
    - cron: '0 2 * * *'  
  workflow_dispatch:  

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: LineageOS remote
        run: |
          git remote add lineage https://github.com/LineageOS/android.git || true
          git fetch lineage lineage-22.1 --depth=1

      - name: Merge
        run: |
          git merge --no-edit lineage/lineage-22.1 || echo "No changes to merge"

      - name: Проверяем статус перед пушем
        run: |
          git status
          git log -1
          git remote -v

      - name: Аутентификация перед пушем
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git config --global credential.helper store
          echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
          git config --global --add safe.directory /github/workspace

      - name: Upload (push only if changes exist)
        run: |
          if git diff --quiet && git diff --staged --quiet; then
            echo "No updates to push"
          else
            git push origin main --verbose
          fi
