name: Update LineageOS Source (aka G(it), L(ineage remote), M(erge), U(pload))

on:
  schedule:
    - cron: '0 2 * * *'  # Запуск каждый день в 02:00 UTC
  workflow_dispatch:  # Возможность запуска вручную

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторий (основной)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Клонируем LineageOS в `lineage-source`
        run: |
          rm -rf lineage-source  # Удаляем старые файлы
          git clone --depth=1 https://github.com/LineageOS/android.git lineage-source

      - name: Настраиваем LineageOS Git
        run: |
          cd lineage-source
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}/lineage-source.git
          git config --global --add safe.directory $PWD

      - name: Пушим изменения в `lineage-source`
        run: |
          cd lineage-source
          if git diff --quiet && git diff --staged --quiet; then
            echo "No updates to push"
          else
            git add .
            git commit -m "Auto-update LineageOS"
            git push origin main --verbose
          fi
