name: Update LineageOS Source (aka G(it), L(ineage remote), M(erge), U(pload))

on:
  schedule:
    - cron: '0 2 * * *'  
  workflow_dispatch:  

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: LineageOS remote
        run: |
          git remote add lineage https://github.com/LineageOS/android.git || true
          git fetch lineage lineage-22.1 --depth=1

      - name: Merge
        run: |
          git merge --no-edit lineage/lineage-22.1 || echo "No changes to merge"

      - name: Аутентификация перед пушем
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Upload
        run: |
          git push origin main || echo "No updates to push"
